### ISSUE TITLE
Solo tables missing from Book of Beasts module

### ISSUE THREAD

**Issue by 9littlebees** [Forbidden-Lands-FVTT/fbl-content-modules#25]
The following tables are not in the Book of Beasts module but are needed for solo play:

- Yes/No Oracle (p 172)
- Helpful / Hazardous Oracle (p172)
- Theme Oracle (p173)
- WIlderness Oracle (p174)
- Kin Oracle (p174)
- Kin Names Oracle (p175)
- Community Traits Oracle (p176)
- NPC Traits Oracle (p176)
- Solo Loot Table (p177)

These just need to be implemented with simple numbered tables, like the existing solo tables.

**Comment by KivoGambino** [comment]
I can confirm and am highly interested in the implementation.

**Comment by aMediocreDad** [comment]
These tables are in the journals for use with cards. That's why they are not implemented as tables. Some of the tables (the ones with columns that correspond to locations, expansions or the like) will require splitting the table into several tables. I am not sure that's a good solution.

At this point I am outside any contract with Free League, and they signed off on the current implementation. I also fielded this implementation with you back before they released. Unfortunately this is just not something I am going to be able to prioritize.
